FROM maven:3.9.6-amazoncorretto-21

WORKDIR /opt

ARG SPRING_SECURITY_USER_NAME
ARG SPRING_SECURITY_USER_PASSWORD
ARG APPLICATION_SECURITY_JWT_SECRET_KEY
ARG APPLICATION_FRONT_CONFIRMATION_URL
ARG SPRING_MAIL_USERNAME
ARG SPRING_MAIL_PASSWORD
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD

ENV SPRING_SECURITY_USER_NAME=${SPRING_SECURITY_USER_NAME}
ENV SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD}
ENV APPLICATION_SECURITY_JWT_SECRET_KEY=${APPLICATION_SECURITY_JWT_SECRET_KEY}
ENV APPLICATION_FRONT_CONFIRMATION_URL=${APPLICATION_FRONT_CONFIRMATION_URL}
ENV SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
ENV SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

COPY . .

RUN mvn clean package -DskipTests -q

ENTRYPOINT ["java", "-jar", "target/signacle-0.0.1-SNAPSHOT.jar"]

EXPOSE 8081
