name: Build and Deploy

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: signacleudf/signacle-api
        registry: docker.io
        tags: ${{ github.ref_name }}, latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        build-args: |
          SPRING_SECURITY_USER_NAME=${{ secrets.SPRING_SECURITY_USER_NAME }}
          SPRING_SECURITY_USER_PASSWORD=${{ secrets.SPRING_SECURITY_USER_PASSWORD }}
          APPLICATION_SECURITY_JWT_SECRET_KEY=${{ secrets.APPLICATION_SECURITY_JWT_SECRET_KEY }}
          APPLICATION_FRONT_CONFIRMATION_URL=${{ secrets.APPLICATION_FRONT_CONFIRMATION_URL }}
          SPRING_MAIL_USERNAME=${{ secrets.SPRING_MAIL_USERNAME }}
          SPRING_MAIL_PASSWORD=${{ secrets.SPRING_MAIL_PASSWORD }}
          SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create deployment files
      run: |
        # Criar arquivo .env
        cat << EOF > .env
        SPRING_SECURITY_USER_NAME=${{ secrets.SPRING_SECURITY_USER_NAME }}
        SPRING_SECURITY_USER_PASSWORD=${{ secrets.SPRING_SECURITY_USER_PASSWORD }}
        APPLICATION_SECURITY_JWT_SECRET_KEY=${{ secrets.APPLICATION_SECURITY_JWT_SECRET_KEY }}
        APPLICATION_FRONT_CONFIRMATION_URL=${{ secrets.APPLICATION_FRONT_CONFIRMATION_URL }}
        SPRING_MAIL_USERNAME=${{ secrets.SPRING_MAIL_USERNAME }}
        SPRING_MAIL_PASSWORD=${{ secrets.SPRING_MAIL_PASSWORD }}
        SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
        SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
        EOF

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "docker-compose.yml,.env,deploy.sh"
        target: "/sistemas/signacle"
        
    - name: Execute deploy script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /sistemas/signacle
          ./deploy.sh
