name: Maven Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
  
    runs-on: ubuntu-latest
  
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: buildd and push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: signacleudf/signacle-api
        registry: docker.io
        tags: ${{ github.ref_name }}, latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    env:
      SPRING_SECURITY_USER_NAME: ${{ secrets.SPRING_SECURITY_USER_NAME }}
      SPRING_SECURITY_USER_PASSWORD: ${{ secrets.SPRING_SECURITY_USER_PASSWORD }}
      APPLICATION_SECURITY_JWT_SECRET-KEY: ${{ secrets.APPLICATION_SECURITY_JWT_SECRETKEY }}
      APPLICATION_FRONT_CONFIRMATION_URL: ${{ secrets.APPLICATION_FRONT_CONFIRMATION_URL }}
      SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
      SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
  
